### ISSUE TITLE
Execution environment

### ISSUE THREAD

**Issue by Manfred** [rubytune/perf_check_ci#29]
Perf Check (PC) was initially developed as a command-line tool and then changed to also be invoked from a Rails application to support CI-like functionality.

The current implementation has some fundamental issues which makes it hard to improve robustness and speed.

## Execution environment

Perf Check CI (PCCI) currently uses the `PerfCheck` class the same way the PC does. In the case of PC this causes the code to run in the target application environment (shell, environment variables, ruby version, Yarn version, Bundler environment, etc) but in the case of the PCCI environment it uses the application environment of the CI Rails application.

Problems manifest in a number of ways:

* The CI and target application **must** run the identical Ruby version or it will break, especially when the Ruby version is specified in the Gemfile.
* Using `Bundler.with_clean_env` does not completely isolate and some of the environment leaks over into the target application. Because the PCCI uses Webpacker, the target application must also **configure** Webpacker or the run will break; not sure why, but just something I experienced with a minimal test project.
* The `PerfCheck` class has to deal with two different execution environments which makes it easy to break without extensive testing.

However, this also has a number of benefits:

* Running test cases only relies on `PerfCheck` middleware in the target application, a part that changes relatively little. This means less maintenance on the target application to keep PCCI running.
* It's not necessary to spawn a new shell when starting the Rails server because the environments **must** be similar, this makes it a tiny bit faster.
* Because the `PerfCheck` code runs in the CI process it can communicate over shared memory (e.g. a `Logger` instance) instead of relying on interprocess communication like pipes or files.

## Moving execution to the target application

Instead of directly using `PerfCheck` it's possible to execute `perf_check` in the target application directory. This automatically causes all the code to run with the correct Ruby version, Bundler environment, etc. This takes away the different between calling PC from the terminal and calling from PCCI.

It would also mean the `perf_check` gem is no longer a dependency of PCCI, but it increases the coupling to the CLI switches and output.

The problem is that it would mean that `perf_check` would require a large rewrite to support structured output.

## Improving stability for the current situation

It might be possible to improve environment stripping (i.e. similar to `Bundler.with_clean_env` but also deal with `rbenv` variables etc).

Currently PC progress and issues are reported through a Logger instance. We also want a channel to report Rails server, migration, and Git issues. Possibly add a toggle to retry a run with increased verbosity to debug server issues.

**Comment by Manfred** [comment]
I can make all my examples work by removing `chdir` and Bundler cleanup and then changing `Process.spawn` in `perf_check/server.rb` to:

```ruby
pid = Process.spawn(
  perf_check_args.merge('HOME' => ENV['HOME']),
  # Use -l to start a login shell to force a fresh ‘user’ environment.
  "bash -l -c \"bundle exec rails server -b #{host} -d -p #{port} -e #{environment}\"",
  chdir: perf_check.app_root, # Spawn the process in the app root
  unsetenv_others: true # Start with an empty environment
)
```

**Comment by sudara** [comment]
> In the case of PC this causes the code to run in the target application environment (shell, environment variables, ruby version, Yarn version, Bundler environment, etc) but in the case of the PCCI environment it uses the application environment of the CI Rails application.

Both Perf Check and Perf Check CI call `perf_check.run` which then runs this code: https://github.com/rubytune/perf_check/blob/c01e6f6fcdbf64c20be7738cf6959d9d792e4959/lib/perf_check/server.rb#L117

In the deamon we were wrapping `perf_check.run` with `Bundler.with_clean_env` https://github.com/rubytune/perf_check_daemon/blob/master/lib/perf_check_daemon/job.rb#L40-L51 — and it seems we are doing it here too.

Restating, you are saying when `bundle exec perf_check` is called from the command line, it runs in the target app's env. Otherwise it's subject to `Bundler.with_clean_env` which has its limitations and still manages to inherit some non-bundler env stuff.

Outside of the leaky env being a surprise/annoying, I probably need to understand a bit more about the drawbacks are...

> Instead of directly using `PerfCheck` it's possible to execute `perf_check` in the target application directory. 
This confuses me because half of what `PerfCheck` actually does is manage executing `bundle exec rails s` in the target directory. Naming is making life hard, but I get what you mean. I think this coupling actually makes life harder for weird reasons: we try and send data back from perf check instead of treat it more like something we are consuming.

I'll chew on it!

**Comment by sudara** [comment]
I believe we used to use `Bundler.with_original_env` just to complicate things...

**Comment by Manfred** [comment]
I think what you are saying is correct. It's all kind of hard to wrap your head around and name properly because it's babies making babies (in process land).

---

I guess the short explanation of the problems is: running `spawn('rails server')` from a Rails or Sidekiq process inherits a lot of environment variables which can break `rails server`.

Only the Bundler ones are taken care of by the `Bundler.*_env` methods and I don't think we would end up with a maintainable solution if we had to support all of the various version managers like `rbenv`, `nvm`, `rvm`, `asdf`, `homebrew`, etc.

One example is: `ENV['RBENV_DIR'] => "/Users/manfred/Code/perf_check_ci/bin"`. This appears to cause the wrong `rails` to execute even though the current working dir is `"/Users/manfred/Code/wrapp"`.

We can't strip the entire environment because some of these variables are actually necessary.  This is why my suggested solution is using a fresh login shell.

I think we could even get away with using an interactive shell session so we only need to spawn one (e.g. the same way Capistrano does, but without the SSH).

**Comment by sudara** [comment]
> my suggested solution is using a fresh login shell.

Ah, does that resolve the problem and let us keep the coupling for logging purposes?

**Comment by Manfred** [comment]
Yes, it's the smallest change we could make to work around this problem. I guess we could even add it as a switch to `perf_check` so you can turn it on and off for projects that might otherwise not run.

**Comment by Manfred** [comment]
Closing this because we've solved it good enough to continue.
