### ISSUE TITLE
Investigate reducing github permissions 

### ISSUE THREAD

**Issue by sudara** [rubytune/perf_check_ci#5]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/472/44924878-f8e9ed00-ad4c-11e8-87ce-a0dde4a226c5.png">

* Do we need write access to the user?
* Can we disable full org access and get granular project access?

**Comment by Manfred** [comment]
Writing specs for the current authentication implementation is going to take more time than implementing GitHub OAuth, so I'm doing that instead.

**Comment by Manfred** [comment]
<img width="588" alt="Screen Shot 2019-07-22 at 15 47 24" src="https://user-images.githubusercontent.com/1195/61637541-05926f00-ac98-11e9-89dd-50a11b2ddf9e.png">
