### ISSUE TITLE
Configure PerfCheck through options instead of parsing arguments

### ISSUE THREAD

**Issue by Manfred** [rubytune/perf_check_ci#57]
Currently we call `perf_check.parse_arguments` to set `perf_check.options` but that requires a roundtrip through CLI options, which doesn't make a lot of sense and gives us less control. The plan is to configure PerfCheck directly through the options by translating Job attributes to options.

**Comment by Manfred** [comment]
The plan is to add a form to create a jobs. Because forms generally have a corresponding accessor on a model it seems like a good idea to add columns for the form fields. Because this is going to require lots of renaming in the code I want to get the naming discussion out of the way first.

I want to propose the following:

```ruby
remove_column :jobs, :arguments

rename_column :jobs, :branch, :experimental_branch
change_column :jobs, :experimental_branch, :text

add_column :jobs, :reference_branch, :text, default: 'master'
add_column :jobs, :task, :string, default: 'compare_branches' # 'compare_paths' (--compare-paths) and 'benchmark' (--quick)
add_column :jobs, :number_of_requests, :integer, default: 20
add_column :jobs, :request_headers, :json
add_column :jobs, :request_paths, :json
add_column :jobs, :use_fragment_cache, :boolean, default: true # --no-caching
add_column :jobs, :run_migrations, :boolean, default: true
add_column :jobs, :diff_response, :boolean, default: true
add_column :jobs, :user_role, :string
add_column :jobs, :user_email, :text
```

**Comment by sudara** [comment]
@Manfred Sweet.

Naming looks good to me except `experimental_branch` — it should probably be `experiment_branch` to pair with `reference_branch` (that way they are both nouns instead of one of them being an adjective, which feels off somehow).

One thing I'm a bit fuzzy on is Perf Check's concept of a `test_case` and how it relates to storing the arguments here. Would it make sense to store `request_path` as a part of a test case?

**Comment by Manfred** [comment]
> Would it make sense to store request_path as a part of a test case?

The implementation for test cases is probably broken at the moment anyway. When you run `perf_check` with `--compare-paths` it does something weird because it migrates, bundles, and restarts the Rails server when switching between request paths.

My idea was to model the interaction as three tasks (and diff, which I will explain at the end) with the same attributes meaning slightly different things.

## Compare branches

```
options.branch = experiment_branch
options.reference = reference_branch
request_paths.each do |request_path|
  perf_check.add_test_case(request_path)
end
```

1. Checkout `experiment_branch`
2. Bundle
3. Rails server start
4. Performs request for all request paths (optionally diff)
5. Rails server stop
6. Checkout `reference_branch`
7. Bundle
8. Rails server start
9. Performs request for all request paths
10. Rails server stop
11. Report difference between branches

## Compare paths

```
options.branch = experiment_branch
options.reference = nil
options[:compare_paths?] = true
request_paths.each do |request_path|
  perf_check.add_test_case(request_path)
end
```

1. Checkout `experiment_branch`
2. Bundle
3. Rails server start
4. Performs request for all request paths (optionally diff)
5. Rails server stop
6. Report difference between paths

## Benchmark

```
options.branch = experiment_branch
options.reference = nil
options.quick = true
request_paths.each do |request_path|
  perf_check.add_test_case(request_path)
end
```

1. Checkout `experiment_branch`
2. Bundle
3. Rails server start
4. Performs request for all request paths
5. Rails server stop
6. Report performance summary

Does not support diff because we're benchmarking.

## Diff branches

```
options.verify_no_diff = true
```

1. Store the response body from the nth request on each branch
2. Diff documents
3. Report difference

## Diff paths

```
options[:compare_paths?] = true
options.verify_no_diff = true
```

1. Store the response body from the nth request on each path
2. Diff documents (may create matrix if we allow more than 2 paths)
3. Report difference

---

I'm not sure what a test case should be in the PerfCheck context. Depending on the task it can either be one per branch, or one per path, or just one when benchmarking? You could also argue that the entire job is a test case.

Internally we don't need multiple things because we just need to fire and gather all the request. If we store the *branch* and *request path* with every response measurement we can group them when reporting.

```
options.request_paths = %w[/companies /projects]
```

**Comment by sudara** [comment]
My only other thought is that `user` is a bit ambiguous, as these options are not at all related to our actual `users` table or `user` in the context of the rest of the app. I don't have any great ideas though: `request_user_role` / `perf_check_user_role` / `login_as_user_role` / `benchmark_as` — or perhaps having the table that these are on be called `arguments` or something.

**Comment by sudara** [comment]
> The implementation for test cases is probably broken at the moment anyway. 

I'm not sure if you mean in PerfCheckCI or PerfCheck, but PerfCheck should be working fine with multiple urls passed to it unless we very recently broke it. Most of the time, people are submitting comparisons between their branch or master with >=1 urls. 

> with `--compare-paths` it migrates, bundles, and restarts the Rails server when switching between request paths.

Yes, this was a contributed feature and not thought through completely when it was added. We could explicitly limit it to 2 urls, as it's not a known use case that people are doing anything other than "hey, does this new API endpoint perform better than the old one?"

> I'm not sure what a test case should be in the PerfCheck context. 

We usually refer to a "job" or a "perf check" as being the whole command and a "test case" being the results of one particular comparison of one url. So a job can have many test cases, each with its own set of results for the url. In the displayed results, we need to display each url along with its results.

**Comment by Manfred** [comment]
Broken is probably not the correct term, but it's kind of weird:

```
$ bundle exec perf_check --requests 2 --compare-paths / /authors
[2019-11-04 17:02:43] =============================================================================
[2019-11-04 17:02:43] PERRRRF CHERRRK! Grab a ☕️  and don't touch your working tree (we automate git)
[2019-11-04 17:02:43] =============================================================================
[2019-11-04 17:02:43] starting rails...
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

[2019-11-04 17:02:46] 
[2019-11-04 17:02:46] Benchmarking /:
[2019-11-04 17:02:46] 	request   latency   server rss   status   queries   profiler data
[2019-11-04 17:02:46] 	 2:	  1.7ms     26MB	  200	   0	   
[2019-11-04 17:02:46] 	 3:	  2.5ms     30MB	  200	   0	   
[2019-11-04 17:02:46] 
[2019-11-04 17:02:46] =============================================================================
[2019-11-04 17:02:46] PERRRRF CHERRRK! Grab a ☕️  and don't touch your working tree (we automate git)
[2019-11-04 17:02:46] =============================================================================
[2019-11-04 17:02:46] re-starting rails...
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

[2019-11-04 17:02:50] 
[2019-11-04 17:02:50] Benchmarking /authors:
[2019-11-04 17:02:50] 	request   latency   server rss   status   queries   profiler data
[2019-11-04 17:02:50] 	 2:	  0.9ms     19MB	  200	   0	   
[2019-11-04 17:02:50] 	 3:	  1.0ms     20MB	  200	   0	   
[2019-11-04 17:02:50] 
[2019-11-04 17:02:52] Checking out master and bundling... 
==== Results ====
reference path:/
test path:/authors
    reference: 0.9ms
  your branch: 2.1094999999999997
       change: 1.2ms (yours is 2.3x slower!!!)
```

**Comment by sudara** [comment]
Ah sorry, I thought you meant benchmarking multiple urls is broken. Yeah, I've never even personally used `--compare-paths`, I don't doubt it's implementation needs help...
